import './globals.css';
import "./leaflet.css";
import { Inter } from 'next/font/google';
import Provider from '@/components/Provider';
import Header from '@/components/Header';

export const metadata = {
  title: 'Phytos App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          <main className='grow'>{children}</main>
        </Provider>
      </body>
    </html>
  )
}
